### ISSUE TITLE
Lost Functions in the WebUI

### ISSUE THREAD

**Issue by Revan335** [imthenachoman/unraid-templates#12]
Hello,

https://forum.rclone.org/t/rclone-encrypt-backup-to-nextcloud/38944 I can't find Option for Local Files, Create Jobs to Backup to Cloud. Revisions and Encryption.

Many Thanks!

Greetings

Revan335

**Comment by imthenachoman** [comment]
The rclone web interface does not have a mechanism to create backups. The container is not doing anything special. It just runs rclone GUI. See https://rclone.org/gui/.
