### ISSUE TITLE
cannot get private key to work

### ISSUE THREAD

**Issue by JabbaDaHutt762** [imthenachoman/unraid-templates#13]
I have just had to delete and rebuild my whole docker client in unraid and when i tried to install nordlynx again I cannot get it to work.

this is in the log file
Key is not the correct length or format: `'
Configuration parsing error

however at the bottom it says its connected, but nothing works routed through the container.

when i ran:
docker run --rm --cap-add=NET_ADMIN -e TOKEN='token' bubuntux/nordvpn:get_private_key
i get the following:
Unable to find image 'bubuntux/nordvpn:get_private_key' locally
get_private_key: Pulling from bubuntux/nordvpn
06d39c85623a: Pull complete 
3e1c241a05c8: Pull complete 
0077b26e8dce: Pull complete 
Digest: sha256:0d91aabb4511d400b01e930654950729a4e859d3c250f61664662b0ed7027c56
Status: Downloaded newer image for bubuntux/nordvpn:get_private_key
Waiting for daemon to start up...
A new version of NordVPN is available! Please update the application.
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
A new version of NordVPN is available! Please update the application.
Technology is already set to 'NORDLYNX'.
A new version of NordVPN is available! Please update the application.
Connecting to United States #9379 (us9379.nordvpn.com)
You are connected to United States #9379 (us9379.nordvpn.com)!
############################################################
IP: 10.5.0.2/32
Private Key:  =
＼(＾O＾)／
############################################################

this also creates an orphaned image in the docker containers:
Image ID: bff3fa2cbb79
bubuntux/nordvpn:get_private_key

i know i have exposed too much here so i will generate a new token and private key if i can have someone tell me what im doing wrong.

when i run curl ifconfig.co from within the nordlynx docker container it just hangs.

**Comment by likwid101** [comment]
I came across this issue when searching for a solution of my own... I was getting the same problem as you. I then found that if I didn't use TOKEN but Username and Password I was able to get the private key. This is the command worked for me. Just change the username and password to the one found in the manual setup section (not your login info for Nord). Let me know if this works or if I'm remembering wrong!

docker run --rm --cap-add=NET_ADMIN -e USER=changeTHIS  -e PASS=changeTHIS bubuntux/nordvpn nord_private_key

*I actually uninstalled all the docker containers for Nord and Nordlynx and ran this (out of frustration) so not sure if you will need to do that

**Comment by JabbaDaHutt762** [comment]
> docker run --rm --cap-add=NET_ADMIN -e USER=changeTHIS -e PASS=changeTHIS bubuntux/nordvpn nord_private_key

this is what returns when i put that string in under the console for the docker:

sh: docker: not found

**Comment by JabbaDaHutt762** [comment]
aha!!!  I got it!  ran that command in the unraid terminal rather than the docker console.  then it returned the following:

docker run --rm --cap-add=NET_ADMIN -e TOKEN=addTOKENhere bubuntux/nordvpn:get_private_key

that in turn did what it was supposed to do and generated the private key to be copied and pasted into the docker container settings.

**Comment by JabbaDaHutt762** [comment]
Solved
