### ISSUE TITLE
Unraid ssh login

### ISSUE THREAD

**Issue by miplos** [imthenachoman/unraid-templates#16]
Hi,

i have to copy and sync a lot of files in unraid. When i try to login over terminal with ssh the standard username/password      rclone/rclone is wrong.
How to get in? With the GUI it's working.

The main reason why i need to ssh in, is that I can't copy folders over the GUI.

Thanks for helping me.

Br

**Comment by imthenachoman** [comment]
Hello. You might want to check the rclone forums. I don't use/have Unraid anymore and I'm not maintaining this app. Sorry!
