### ISSUE TITLE
WebUI and Port Mappings issues

### ISSUE THREAD

**Issue by diegomontanaduarte** [imthenachoman/unraid-templates#3]
I'm unable to see the WebUI option using your Rclone template. Also for unknown reason the Port Mappings it's not showing

![image](https://user-images.githubusercontent.com/2682853/159576047-87097341-c95f-4ea7-a20e-13aebdfc6d4a.png)

**Comment by imthenachoman** [comment]
Strange. Can you share a screenshot of the container config?

**Comment by diegomontanaduarte** [comment]
<?xml version="1.0"?>
<Container version="2">
  <Name>Rclone</Name>
  <Repository>rclone/rclone</Repository>
  <Registry>https://hub.docker.com/r/rclone/rclone/</Registry>
  <Network>br0</Network>
  <MyIP>10.11.0.54</MyIP>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://github.com/imthenachoman/unraid-templates/issues</Support>
  <Project/>
  <Overview>This unRAID application is a Docker container running rclone's built-in GUI (https://rclone.org/gui/).&#xD;
&#xD;
The default username and password is rclone/rclone. To change it, modify the `--rc-user` and `--rc-pass` values foor `Extra Parameters` in unRAID's container configuration.</Overview>
  <Category>Backup: Cloud: Tools:</Category>
  <WebUI>http://[IP]:[PORT:5572]/</WebUI>
  <TemplateURL>https://raw.githubusercontent.com/imthenachoman/unraid-templates/master/Nacho-Rclone-Native-GUI.xml</TemplateURL>
  <Icon>https://raw.githubusercontent.com/rclone/rclone/master/graphics/logo/logo_symbol/logo_symbol_color_256px.png</Icon>
  <ExtraParams/>
  <PostArgs>rcd --rc-web-gui --rc-web-gui-update --rc-web-gui-force-update --rc-web-gui-no-open-browser --rc-addr 10.11.0.54:5572 --rc-user admin --rc-pass **********</PostArgs>
  <CPUset>1,2</CPUset>
  <DateInstalled>1648031808</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Description>This unRAID application is a Docker container running rclone's built-in GUI (https://rclone.org/gui/).&#xD;
&#xD;
The default username and password is rclone/rclone. To change it, modify the `--rc-user` and `--rc-pass` values foor `Extra Parameters` in unRAID's container configuration.</Description>
  <Networking>
    <Mode>br0</Mode>
    <Publish>
      <Port>
        <HostPort>5572</HostPort>
        <ContainerPort>5572</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
    </Publish>
  </Networking>
  <Data>
    <Volume>
      <HostDir>/mnt/user/appdata/rclone</HostDir>
      <ContainerDir>/config/rclone</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment>
    <Variable>
      <Value>Europe/Lisbon</Value>
      <Name>America/New_York</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>100</Value>
      <Name>PGID</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>99</Value>
      <Name>PUID</Name>
      <Mode/>
    </Variable>
  </Environment>
  <Labels/>
  <Config Name="WebUI" Target="5572" Default="5572" Mode="tcp" Description="Container Port: 5572" Type="Port" Display="always" Required="true" Mask="false">5572</Config>
  <Config Name="PHP_TZ" Target="America/New_York" Default="America/New_York" Mode="" Description="Container Variable: PHP_TZ" Type="Variable" Display="always" Required="true" Mask="false">Europe/Lisbon</Config>
  <Config Name="PGID" Target="PGID" Default="100" Mode="" Description="Container Variable: PGID" Type="Variable" Display="advanced-hide" Required="true" Mask="false">100</Config>
  <Config Name="PUID" Target="PUID" Default="99" Mode="" Description="Container Variable: PUID" Type="Variable" Display="advanced-hide" Required="true" Mask="false">99</Config>
  <Config Name="AppData Config Path" Target="/config/rclone" Default="/mnt/user/appdata/rclone" Mode="rw" Description="Container Path: /config/rclone" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/rclone</Config>
</Container>

**Comment by imthenachoman** [comment]
What is the custom network type you have? I have never tried that before. Does normal traffic routing still work with that?

**Comment by diegomontanaduarte** [comment]
Adding the extra parameter below resolved the issue.

-p '5572:5572/tcp'

![image](https://user-images.githubusercontent.com/2682853/160190006-0040a544-8bc9-4519-bd7f-195f22e9631f.png)

**Comment by imthenachoman** [comment]
Strange. What version of unRAID are you on? I didn't have to do that. It happened automatically by setting the port in the container config.

**Comment by hellopanictech** [comment]
I had to do this too, using a custom network just like the OP. I'm on unRAID 6.9.2, but I think this is more related to being on our own customer networks.

**Comment by imthenachoman** [comment]
Ah. I guess if you use a custom neetwork then you have to explicitly pass the ports.
